# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  run:
    desc: run server instance
    aliases: [dev, r]
    cmds:
      - go run server/main.go

  format:
    desc: format
    cmds:
      - gofmt -s -w .

  lint:
    desc: lint
    cmds:
      - golangci-lint run ./...

  scan:
    desc: security scan
    cmds:
      - govulncheck ./...
      - gosec ./...

  check:
    desc: run checks
    cmds:
      - task: format
      - task: lint
      # - task: scan
