# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  clean:
    cmds:
      - rm -rf bin && mkdir bin

  install:
    desc: install dependencies
    aliases: [i]
    cmds:
      - go mod tidy

  run:
    desc: run server instance
    aliases: [dev, r]
    cmds:
      - go run server/main.go

  format:
    desc: format
    cmds:
      - gofmt -s -w .

  lint:
    desc: lint
    cmds:
      - golangci-lint run ./...

  scan:
    desc: security scan
    cmds:
      - govulncheck ./...
      - gosec ./...

  check:
    desc: run checks
    aliases: [c]
    cmds:
      - task: format
      - task: lint
      # - task: scan

  build-cli:
    desc: build cli
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o bin/cli ./cli

  build-server:
    desc: build server
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o bin/server ./server

  build:
    desc: build binaries
    cmds:
      - task: build-cli
      - task: build-server

  docker:up:
    desc: start docker compose
    interactive: true
    cmds:
      - docker compose up -d
